# Generated by Django 4.1 on 2022-11-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='card.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='card.сonnector', verbose_name='Видеоразъем'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cooler',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Колличество вентиляторов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frequency',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Частота видеопроцессора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lhr',
            field=models.BooleanField(default=True, verbose_name='LHR'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='card.manufacturer', verbose_name='Производитель графического процессора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='card.memory', verbose_name='Тип памяти'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='card.power', verbose_name='Кабеля питания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='card.processor', verbose_name='Графический процессор'),
        ),
    ]
