# Generated by Django 4.1 on 2022-11-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_cart_alter_product_category_alter_product_connector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='complete',
            new_name='completed',
        ),
    ]
